app1/urls.py
from django.urls import path
from . import views
app_name='app1'
urlpatterns=[
    path('hello/',views.hello,name='hello'),
    path('',views.index,name='index'),
    path('signup/',views.signup,name='signup'),
]

project9/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('app1.urls')),
]

app1/models.py
from django.db import models
# Create your models here.
class Register(models.Model):
    Name=models.CharField(max_length=8)
    Age=models.IntegerField()
    Place=models.CharField(max_length=8)
    Email=models.EmailField()
    Password=models.CharField(max_length=8)

app1/forms.py
from django import forms
from. models import Register
class RegisterForm(forms.ModelForm):
    Password=forms.CharField(widget=forms.PasswordInput,max_length=8,min_length=2)
    ConfirmPassword=forms.CharField(widget=forms.PasswordInput,max_length=8,min_length=2)
    class Meta():
        model=Register
        fields='__all__'
        

app1/views.py
from django.shortcuts import render,redirect
from django.contrib import messages
from  django.http import HttpResponse
from . forms import RegisterForm
from . models import Register
# Create your views here.
def hello(request):
    return HttpResponse("welcome to project9")

def index(request):
    name='try'
    return render(request,'index.html',{'data':name})
# def signup(request):
#     form=RegisterForm()
#     return render(request,'signup.html',{'form':form})


def signup(request):
    if request.method=='POST':
        form=RegisterForm(request.POST)
        if form.is_valid():
            name=form.cleaned_data['Name']
            age=form.cleaned_data['Age']
            place=form.cleaned_data['Place']
            email=form.cleaned_data['Email']
            password=form.cleaned_data['Password']
            confirmpassword=form.cleaned_data['ConfirmPassword']
            user=Register.objects.filter(Email=email).exists()

            if user:
                messages.warning(request,'email already exits')
                return redirect('/signup')
            elif password!=confirmpassword:
                messages.warning(request,'password mismatch')
                return redirect('/signup')
            else:
                tab=Register(Name=name,Age=age,Place=place,Email=email,Password=password)
                tab.save()
                messages.success(request,'data entered')
                return redirect('/')

    else:
        form=RegisterForm()
    return render(request,'signup.html',{'form':form})

app1/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>project9</title>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <p> login page </p>
    <a href="{% url 'app1:signup' %}">signup</a>
</body>
</body>
</html>

app1/templates/signup.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <form action="" method="post">
        {% csrf_token %}
        <table>
            <tr>{{form.as_table}}</tr>
        </table>
        <input type="submit" value="Signup">
    </form>

</body>
</html>